version: "3.7"

services:
    web:
        image: nginx:latest
        ports:
            - 80:80
        volumes: 
            - ./:/www
            - ./site.conf:/etc/nginx/conf.d/site.conf
        networks: 
            - hibrido
        depends_on:
            - php
    php:
        build: . 
        volumes: 
            - ./:/www
        expose: 
            - 9000
        networks: 
            - hibrido
    db:
        image: mysql:latest
        networks: 
            - hibrido
        command: 
            - "--default-authentication-plugin=mysql_native_password"
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: hibrido
            MYSQL_DATABASE: hibrido
        volumes: 
            - ./dbdata:/var/lib/mysql
networks: 
    hibrido:
        driver: bridge
            